add task
Borunia/13.7_zadanmie pull request #1
Opened 2018-03-13 19:32 UTC by Borunia

2018-03-13 21:54 UTC, Borunia commented
add finished task

2018-03-19 14:25 UTC, matwjablonski requested changes

2018-03-19 14:25 UTC, matwjablonski commented on index.js
> +/*
remove commented code

2018-03-19 14:25 UTC, matwjablonski commented on index.js
> +
on the end of document leave just one empty line

2018-03-19 17:14 UTC, matwjablonski approved these changes

2018-03-25 11:40 UTC, merged